### Проверяем калькулятор
GET http://localhost:8080/calculator/plus?num1=0&num2=2

### Проверяем деление
GET http://localhost:8080/calculator/divide?num1=32&num2=0

### Проверяем умножение
GET http://localhost:8080/calculator/multiply?num1=32&num2=33
